# -*- coding: utf-8 -*-
"""8-2-25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16tHqRFLDWfEbaK-jZOUkRDGhA9PIV6Hm
"""

print("I am going \nCollege for \nlearning nlp")

print("I am going \nCollege for\tlearning nlp")

print("I am going College for \rlearning nlp")

import re

string="007 james bond wants to learn the python"
pattern=r'\d+'
matching=re.match(pattern,string)
matching.group()

string="007 james bond wants to learn the python"
pattern=r'\d+'
matching=re.search(pattern,string)
matching.group()

string="007 james bond wants 008 to learn 87 the python"
pattern=r'\d+'
matching=re.findall(pattern,string)
matching

string="007 james bond wants 008 to learn 89 the python"
pattern=r'\d+'
matching=re.sub(pattern,'#',string)
matching

# Test case
text = """
Hello world! Contact us at info@example.com or support123@company.org. Follow us on social media: #AI #MachineLearning.
Visit <a href="http://example.com">our website</a> for more details. This is a test with number 1234.
"""

import re
from html import unescape

def clean_text(text):
    # Extract email addresses
    emails = re.findall(r'[\w\.-]+@[\w\.-]+', text)

    # Extract hashtags
    hashtags = re.findall(r'#\w+', text)

    # Remove numbers
    text = re.sub(r'\d+', '', text)

    # Remove HTML tags
    text = re.sub(r'<.*?>', '', text)

    # Normalize whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    # Unescape HTML entities
    text = unescape(text)

    return {
        "cleaned_text": text,
        "emails": emails,
        "hashtags": hashtags
    }

# Example usage
test_text = """
Hello world! Contact us at info@example.com or support123@company.org. Follow us on social media: #AI #MachineLearning.
Visit our website for more details. This is a test with number .
"""

result = clean_text(test_text)
print(result)

pattern=r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'
emails=re.findall(pattern,text)
emails

hashtags = re.findall(r'#\w+', text)
hashtags

