# -*- coding: utf-8 -*-
"""DAY-22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EFkLduZWnphaJvbTxFfXrdPjoBhnm1mB
"""

import spacy

# Load the SpaCy English language model
nlp = spacy.load("en_core_web_sm")

# The sentence to analyze
sentence = "NLP is amazing and fun to learn."

# Process the sentence using SpaCy
doc = nlp(sentence)

# Perform part-of-speech tagging and print the results
print("Token\tPOS\t\tTag Description")
print("-" * 30)
for token in doc:
    print(f"{token.text}\t{token.pos_}\t\t{spacy.explain(token.pos_)}")